
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const UserRole = {
  Admin: 'Admin',
  Vendor: 'Vendor',
  Customer: 'Customer'
} as const

export type UserRole = (typeof UserRole)[keyof typeof UserRole]


export const UserStatus = {
  Active: 'Active',
  Pending: 'Pending',
  Suspended: 'Suspended'
} as const

export type UserStatus = (typeof UserStatus)[keyof typeof UserStatus]


export const CertificationStatus = {
  Pending: 'Pending',
  Approved: 'Approved',
  Rejected: 'Rejected'
} as const

export type CertificationStatus = (typeof CertificationStatus)[keyof typeof CertificationStatus]


export const OrderStatus = {
  Pending: 'Pending',
  Confirmed: 'Confirmed',
  Shipped: 'Shipped',
  Delivered: 'Delivered',
  Cancelled: 'Cancelled'
} as const

export type OrderStatus = (typeof OrderStatus)[keyof typeof OrderStatus]
